id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'Needs: author feedback'
      - noActivitySince:
          days: 4
      - isNotLabeledWith:
          label: 'Status: no recent activity'
      actions:
      - addLabel:
          label: 'Status: no recent activity'
      - addReply:
          reply: This issue has been automatically marked as stale because it is marked as needing author feedback but has not had any activity for **4 days**. It will be closed if no further activity occurs **within 3 days of this comment**. Thank you for your interest in Outlook development!
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'Needs: author feedback'
      - hasLabel:
          label: 'Status: no recent activity'
      - noActivitySince:
          days: 3
      actions:
      - addReply:
          reply: This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 1
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'Type: programming question'
      actions:
      - addReply:
          reply: Thanks for your interest in Outlook development! Feedback here is intended for reporting problems with the Outlook developer *documentation*. Can you please post your question to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/office-addins-dev.html)? By posting how-to questions like this to Q&A, you'll not only be able to reach a broader audience of folks who have expertise in the area, but will also enable others to benefit from any answers that are provided there. Thanks!
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 1
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'Type: product feature request'
      actions:
      - addReply:
          reply: Thanks for your interest in Outlook development! Feedback here is intended for reporting problems with the Outlook developer *documentation*. Can you please post this feature request to [Microsoft Feedback](https://feedbackportal.microsoft.com/feedback/forum/89a8afa3-2e1c-ec11-b6e7-0022481f8472)? Feature Requests submitted to **Microsoft Feedback** are regularly reviewed by the product teams as they plan future releases. Thanks!
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isOpen
      - isIssue
      - hasLabel:
          label: Resolved
      - noActivitySince:
          days: 1
      actions:
      - removeLabel:
          label: 'Needs: attention :wave:'
      - removeLabel:
          label: 'Needs: author feedback'
      - addReply:
          reply: This issue has been marked resolved and will be closed. ${issueAuthor}, if you do not believe this issue has been resolved, please leave a comment with the text `#reopen` and an explanation of what still needs to be addressed, within the next 7 days.
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isOpen
      - hasLabel:
          label: 'Type: support request'
      - hasLabel:
          label: 'Area: actionable messages'
      actions:
      - addReply:
          reply: Thanks for your interest in Outlook development! Feedback here is intended for reporting problems with the Outlook developer *documentation*. Microsoft support staff do not monitor this repository, and we are limited in our ability to provide assistance outside of the documentation. If this issue persists, please email [onboardoam@microsoft.com](mailto:onboardoam@microsoft.com) or contact Microsoft support.
      - removeLabel:
          label: 'Needs: attention :wave:'
      - removeLabel:
          label: 'Status: no recent activity'
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isOpen
      - isIssue
      - hasLabel:
          label: 'Type: support request'
      - isNotLabeledWith:
          label: 'Area: actionable messages'
      actions:
      - addReply:
          reply: >-
            Thanks for your interest in Outlook development! Feedback here is intended for reporting problems with the Outlook developer *documentation*. For support with Outlook development, please use one of the following options.


            - [Office assisted support](https://developer.microsoft.com/office/docs#officesupport)

            - [Microsoft Q&A](https://docs.microsoft.com/answers/products/)
      - closeIssue
    eventResponderTasks:
    - if:
      - payloadType: Issues
      - isAction:
          action: Opened
      - not: isAssignedToSomeone
      then:
      - addLabel:
          label: 'Needs: triage :mag:'
      description: 
    - if:
      - payloadType: Issues
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: 'Status: no recent activity'
      then:
      - removeLabel:
          label: 'Status: no recent activity'
      description: 
    - if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: 'Status: no recent activity'
      then:
      - removeLabel:
          label: 'Status: no recent activity'
      description: 
    - if:
      - payloadType: Issue_Comment
      - isAction:
          action: Created
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: 'Needs: author feedback'
      then:
      - addLabel:
          label: 'Needs: attention :wave:'
      - removeLabel:
          label: 'Needs: author feedback'
      description: 
    - if:
      - payloadType: Pull_Request
      then:
      - inPrLabel:
          label: 'Status: in PR'
      description: 
    - if:
      - payloadType: Issues
      - labelAdded:
          label: 'Status: in PR'
      - hasLabel:
          label: 'Status: under investigation'
      then:
      - removeLabel:
          label: 'Status: under investigation'
      description: 
      triggerOnOwnActions: true
    - if:
      - payloadType: Issues
      - labelAdded:
          label: 'Status: in PR'
      - hasLabel:
          label: 'Status: in backlog'
      then:
      - removeLabel:
          label: 'Status: in backlog'
      description: 
      triggerOnOwnActions: true
    - if:
      - payloadType: Issues
      - labelAdded:
          label: 'Status: in PR'
      - hasLabel:
          label: 'Needs: attention :wave:'
      then:
      - removeLabel:
          label: 'Needs: attention :wave:'
      description: 
      triggerOnOwnActions: true
onFailure: 
onSuccess: 
